-- AlterTable
ALTER TABLE "CartItem" ADD COLUMN     "addedAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Coupon" ADD COLUMN     "sold" BOOLEAN NOT NULL DEFAULT false;
